baseURL = 'https://golings.vercel.app/'
languageCode = 'en-us'
title = 'Golings Site'
theme = "blog"

[[params.socialIcons]]
name = "github"
url = "https://github.com/mauricioabreu/golings"

# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'hrdark'
    tabWidth = 4

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'About'
    url = '/'
    weight = 10
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="installing"
    name = 'Installing'
    url = '/installing'
    weight = 10
  [[menu.main]]
    pageRef="exercices"
    name = 'Exercises'
    url = '/exercises/'
    weight = 20

[params]
  sitename = "Golings"
  pageSource = "https://github.com/Grubba27/golings-site"
  defaultColor = "light" # set default color mode: dark or light
  description = "Rustlings, but for Go"
  exercises = "https://github.com/mauricioabreu/golings/blob/main/exercises"
  image = "gopher_team.png"
  ogimage = "gopher_team.png"

[params.author]
  avatar = "Go-Logo_Blue.png"
  intro = "Learning Go by solving problems"
  name = "Made with ❤️ by Mauricio Abreu and Gabriel Grubba"
  description = "rustlings but for golang this time."